baseURL = 'https://blog-bn0.pages.dev/'
languageCode = 'zh-cn'
title = 'LuluHome'
theme = 'introduction'

[params]
    favicon                      = "img/favicon.svg"           # Path to favicon file
    themeStyle                   = "auto"                  # Choose "light" or "dark" or "auto"
    showMenu                     = false                   # Show navigation menu
    fadeIn                       = true                    # Turn on/off the fade-in effect
    customCSS                    = ["vendor/photoswipe/photoswipe.css", "custom.css"] # Include custom css files placed under assets/
    customJS                     = ["js/site.js"]          # Include custom JavaScript files placed under assets/

    [params.home]
        introHeight              = "fullheight"            # Input either "medium" or "large" or "fullheight"
        showLatest               = false                   # Show latest blog post summary
        localTime                = false                   # Show your current local time in contact section
        timeZone                 = "Asia/Shanghai"         # Your timezone
        timeFormat               = "zh-CN"                 # Language specific format to use

[markup]
  [markup.goldmark.renderer]
    unsafe = true # Required for some theme features
